addons:
  ssh_known_hosts: github.com

jobs:
  include:
  # - stage: tests
  #   os: osx
  #   osx_image: xcode11.1
  #   language: node_js
  #   node_js: lts/*
  #   name: Unit Tests
  #   before_script:
  #   - npm install -g npm@latest
  #   script:
  #   - npm ci
  #   - npx jest --ci --passWithNoTests
  - stage: deploy-staging-ios
    # if: branch IN ("master")
    os: osx
    osx_image: xcode11.5
    language: node_js
    node_js:
    - node
    - lts/*
    before_install:
    - git clean -d -f
    # - gem install bundler:2.0.2
    # - bundle install
    before_script:
    - openssl aes-256-cbc -K $encrypted_db4416ddba70_key -iv $encrypted_db4416ddba70_iv 
      -in ./ci/certs_key.enc -out ./ci/certs_key -d
    - eval "$(ssh-agent -s)"
    - chmod 600 ./ci/certs_key
    - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - echo -e "Host github\nHostName github.com\nUser git\nIdentityFile /home/travis/build/revelry-foundation/nightingale-mobile/ci/certs_key\nIdentitiesOnly yes" >> ~/.ssh/config
    - ssh-add ./ci/certs_key
    - git commit --allow-empty -m "Empty commit"
    - git remote add ssh-origin git@github.com:revelry-foundation/nightingale-mobile.git
    - git push ssh-origin verbose-match-fix-travis
    script:
    - echo "fastlane ios beta"
    after_script:
    - rm ./ci/certs_key
env:
  global:
  - secure: cgpi13Wa8js7P2eLr2VjPhRrlxlCZJSzPvu9LHR98kCRhms2wshVMWcnx32GyQ2pbvSkwS/90+VWS6pkz6GhhFt+lxndWprzt2yKAyywMihIsJ1Zz8q+jMX3fyq5Pkct/Ey5r7h0t6gb0w/tj93+ojcQcH+ZVT25ppbxYsb0adVyqtm+6V3jk1slpcTRCgaROS+fVSHsVwiuIgne5WXfdjhnV472LmFoCyLcK3VpDpwy32be3z8KMWk3jn2M4y0xFvuMkQDhLCMythDBNSnnuS6FKnK0GNIEs90LoARvbzwfGyrn2uvKfGjto044Ml2kukLKriMOMd5xrIrNChiTfBEBixGZ0MMXEUFW0y1fWz29wR1ohuWxN9kaYXi7tqggl1z2vAM0ipdIEpewPavqwFVFnQSvXz8+dcZHFbAQJ6QkovEoO79PBzZSzLhA8fMdRFkXl6tc3bl2FBot1Z+iisGtEdJoWvmDv1J7AqoUCOV1Okc4IQTFJB2KLUSLBwGI3LjXWwg5tkIlL6JAPATjVshMiMKrE8cItetJXfFXGsWlaMk2l2lSI2Iq4UQGqZwzG5mPcHYrlUHV1r624GBnwxH3lZIHOB3b1id61Vm6qyeqdpfUt1xArESmYUbOmvmkg+hcqtswNYrX2jXhX66bewABKibhAQdW/9gXz0gWFlU=
  - secure: WVJl5iuzF1U7romA2VIfcemkcDVj+6L4rHSR/mxzHaQS0cSDa6QDnxlhCUUJeztwcTsqOXrNjtL9sVYkEdWV26KhT/EabMzPYy7Dg7lIS9vep5sgjdXcQwGWwckUJDcdfF/pCbToMsOvghKzg22lSX4+zOtVexNA2+ygXpMow+nKeGZApIKndZiyBCDEbwdq1Bs/0kAR2OH18NcPO35Q5H4JEfrSoioGSB6GYVqcDig+7TuYZ5OqrKlZHQS7p72gBoj67fLZXmfBoZYdZHhBskchJvAuKjCa/HAK6Kxw9LbqsarK5mg6qCDf3a3mhnltGgomCjmtSHVokRtdShzQz1SpZuCti/iKB5TUKaQR3QUQEdxBICh/jp/rxOquiyvczcUHQMRvM0JC3YdToDkfQhLOyC8N+oCt7SqjEiDrBHcX5sRAgZiIpw+RqEoNO433ji5ZGUF0T5+qfiCNnqU4esmkEIEX/kYDZ+uyC79kjoEKFfmGaP89ygItzhfXebn1W1XuNZz7ZuRLTLyHDKzSVIAhw/Yocu+07VjBRNjg31icBkb29/yStbJVZH85JkNNJ6g3VyezDePcM4FF7fg5P79aRXrVJyzhI1nuMQoGflQyLxpNngDC0ojkjl+pmZsLiM9fESJPSvzNYlDziYHXWUoFxMyLD15M1Nbext1ioTQ=
  - secure: Dkc+9Ku8clgXPeQic4ifGRPPdqyt061ezs+sGt1yUr2xHI1C8YOQiBSfhCeIe1wafc/cbgpDSR9V7Nh55UzVq2Sxmv89/bEYf6NcqSjkkP0ODXPDk+d+rjVaA+fNUapsRw1c+D0BDI2vgNhuixsSbmwRjFwJ6047b5Wyyu/O4lUolY6xm8q69JurzwP1vIdY/tquL7vVx9IM2H1a6zJk1Vj+N2IWlWv4ECdHuUiKTZelHhU07ilxgGofJ1Y9fZBSX0tVE0vYSXtZxbQMbczLXfvKxBOo+hVfBdsWQxEE4dfYd/cKlZl8nbxSKZ/1j4W8sKTi6COvOOMimbT8/LKiBKPohGna6zOXZm/jTE+W5Yw7puDonmstMgwivMv5XgMqQpwt32XPd4A6NVIn6zlKxFPBvsHO9UTrsTvkAm0ux9VfE9I9GrbSGVds16qeIhaiLxZLP6o5NV4BoW7f685SiZ1STQhYITb0Z0NXyQnDHo/t46gksraOIb2qqH6IzKz0rABOIrW5yLzxwKb78EfZaslxBI8eu9VtplazjjM+AtbRWZv19DKp3RSdioOhiSq8qbQOhLpaVruCqpas1I4MEqfdrQwGUF9g2sQNTXA5Du3DrgW651uURE9u5HPU2A2ke1dWEAq8NsAVWV+ZEOeidslx0tslrOHgdr0JJiuGt8Y=
  - secure: pMeX8kS1iPccoYViOLlEkSCyABeCeQ2TEfj3Xs+iRZN6wpNIdI02smLly6T4X+rxzeoMs6uyPF3v12Hk/vk3aoHDvpPI8ix6XMgL6UKSiw2Gjlu4tXpXpRB2tiPUaUqzNdgl1QuqYW3RiDlZ3QaGvxiv4K6DIdUmXfVXllZltiSMnKCQ1Fj1/7sf2lAe9DYUUmDxhikQFFhaIUowytOF92yb5c5aDb1GTABbArp3TwhH2B2ej2oikW1BBa4aaiaEw05RDA1MBSUawVNTv+DvglOVe8a097RBrqOIpbU07bEHN5vTV8b0j+MeZBUNbEL8spifdsZ5hi3BQr1wQ+WUOq8wGQ8O/vbHVhUIYU0suWWyMY09e0i2FW/6OVNrPKMi3/uoXQYRrLJtxE+fclF/TAqFBnPf8qD+gtMS6hUPStV6fhhrjLpVeqFNyyLy0JGAa8+zf5G1Rfs0H6SyoJQUx5TSKgad7LwjOX4fqMWrgJBKWVD54VBoxF9lFfG0PrnjGgW/RGaD4L08foDzaCqa4hrGoxyO7kMcitu0UR9tcdahBnuKENpHbJFz7JrqftbvAhibmDBKcV5Taua/cSqCnC0H4OJOUdhxj0PFM7qtVOtUXpiROmtrm6iwSjgBVmw4R3zBjaY+p5mbzwxemSl/qNF3WKkkmBcIaYqiKn9LMAo=
